add property row to textarea
wcm-io/io.wcm.caconfig.editor pull request #6
Opened 2022-11-14 09:30 UTC by orangeven

add property rows to textarea

2022-11-14 19:36 UTC, stefanseifert requested changes
please also update the changelog

2022-11-14 19:36 UTC, stefanseifert commented on bundle/src/main/webapp/app-root/clientlibs/io.wcm.caconfig.editor/js/widgets/property-input-textarea.directive.js
> +      scope.textareaRows = props.textareaRows;
throws: _ReferenceError: props is not defined_

2022-11-15 17:20 UTC, orangeven commented on bundle/src/main/resources/angularjs-partials/propertyInputTextarea.html
> +              rows="{{textareaRows}}"
I tried `ng-attr-rows="{{textareaRows || undefined }}"`. rows attribute is now skipped as expected if textareaRows is not defined. but `ng-attr-rows="{{textareaRows || undefined }}"` is already rendered in the html markup. is it the expected hehavior?

2022-11-16 08:57 UTC, stefanseifert commented on bundle/src/main/resources/angularjs-partials/propertyInputTextarea.html
> +              rows="{{textareaRows}}"
you're right - ng-attr-rows seems to be always present. i've reverted to the your previous version, the property "rows" is not present if textareaRows is not set.

2022-11-16 08:57 UTC, stefanseifert approved these changes

2022-11-16 08:57 UTC, merged